services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
