services: 
  app:
    build:  .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3000:80"
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf 
    environment:
      - WATCHPACK_POLLING=true
    