on:
  push:
    branches: [ master, main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find dist/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.yandrydev.com
        username: yandrydev@yandrydev.com
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
